<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://github.com/SkatAI/skatai_deeplearning/blob/master/notebooks/les_tenseurs.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Executer dans Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/SkatAI/skatai_deeplearning/blob/master/notebooks/les_tenseurs.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />sur GitHub</a>
  </td>
</table>

# Deep learning par la pratique - manipulation des tenseurs

Dans ce notebook vous allez vous familiariser avec la manipulation des tenseurs avec tensorflow.

- quelques opérations sur les tenseurs
- comment charger une dataframe
- comment charger des images et les transformer




In [ ]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.15.0


## operations de base

### Création des tenseurs

On crée des tenseurs de rang 0 à 5 à partir d'objets numpy

In [ ]:
# Rank 0 Tensor (Vector)
tensor_rank_0 = tf.constant(22)
print("Rank 0 Tensor:", tensor_rank_0)

Rank 0 Tensor: tf.Tensor(22, shape=(), dtype=int32)


In [ ]:
# Rank 1 Tensor (Vector)
tensor_rank_1 = tf.constant([1, 2, 3, 4, 5])
print("Rank 1 Tensor:", tensor_rank_1)

Rank 1 Tensor: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [ ]:
# Rank 2 Tensor (Matrix)
tensor_rank_2 = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Rank 2 Tensor:", tensor_rank_2)


Rank 2 Tensor: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


#### A vous

Chargez un fichier csv (Iris) dans un tenseur
en utilisant la fonction
`tf.convert_to_tensor()`

- qu'est ce qui se passe et pourquoi ?


In [ ]:
# chargez un fichier csv (Iris) dans un tenseur
# en utilisant la fonction
# tf.convert_to_tensor()

# load iris.csv
import pandas as pd

url = "https://gist.githubusercontent.com/Thanatoz-1/9e7fdfb8189f0cdf5d73a494e4a6392a/raw/aaecbd14aeaa468cd749528f291aa8a30c2ea09e/iris_dataset.csv"
data = pd.read_csv(url)
print(data.head())
# votre code



   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

        target  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa  


In [ ]:
# charger une image

image_file = 'etretat.jpg'
image = tf.io.decode_jpeg(tf.io.read_file(image_file), channels=1)
# Print the shape of the tensor
print("Tensor shape:", image.shape)
